import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import { CalendarDays, LogOut, RefreshCw, ShieldCheck, TrendingUp, Users, WalletCards } from 'lucide-react';
import { supabase, Invoice, Role } from './lib/supabase';
import { fetchInvoices, syncOmni } from './lib/data';
import './styles.css';

const money = (n:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const monthAgo = () => { const d=new Date(); d.setMonth(d.getMonth()-1); return d.toISOString().slice(0,10); };
function Login(){ const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); async function submit(e:React.FormEvent){e.preventDefault();setBusy(true); const {error}=await supabase.auth.signInWithPassword({email,password}); setMessage(error?.message||'');setBusy(false);} return <main className="login"><div className="login-card"><div className="brand-mark">N</div><h1>Supplier Analysis</h1><p className="muted">Sign in to your procurement workspace</p><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} /></label>{message&&<p className="error">{message}</p>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></div></main> }
function App(){ const [session,setSession]=useState<any>(null); const [role,setRole]=useState<Role>(); const [invoices,setInvoices]=useState<Invoice[]>([]); const [from,setFrom]=useState(monthAgo()); const [to,setTo]=useState(new Date().toISOString().slice(0,10)); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session) supabase.from('profiles').select('role').eq('id',session.user.id).single().then(({data})=>setRole(data?.role))},[session]);
 async function load(){setLoading(true);setMessage('');try{setInvoices(await fetchInvoices(from,to))}catch(e:any){setMessage(e.message)}finally{setLoading(false)}} useEffect(()=>{if(session)load()},[session]);
 async function sync(){setLoading(true);try{await syncOmni(from,to);await load();setMessage('Omni invoices synchronised.')}catch(e:any){setMessage(e.message)}finally{setLoading(false)}}
 const ranked=useMemo(()=>Object.values(invoices.reduce((a:any,i)=>{a[i.supplier_name]??={supplier:i.supplier_name,value:0,count:0};a[i.supplier_name].value+=Number(i.usd_amount??i.amount*i.usd_rate);a[i.supplier_name].count++;return a},{})).sort((a:any,b:any)=>b.value-a.value).slice(0,10),[invoices]); const total=ranked.reduce((x:any,y:any)=>x+y.value,0); const suppliers=ranked.length;
 if(!session)return <Login/>; return <div className="shell"><aside><div className="logo"><span>N</span> NEXUS</div><div className="side-title">PROCUREMENT<br/><b>INTELLIGENCE</b></div><nav><a className="active"><TrendingUp size={18}/> Overview</a><a><Users size={18}/> Suppliers</a><a><WalletCards size={18}/> Invoices</a></nav><div className="side-bottom"><div className="role"><ShieldCheck size={16}/><span>{role?.replace('_',' ')||'User'}<small>{session.user.email}</small></span></div><button className="ghost" onClick={()=>supabase.auth.signOut()}><LogOut size={16}/> Sign out</button></div></aside><main className="content"><header><div><p className="eyebrow">SUPPLIER ANALYSIS / OVERVIEW</p><h1>Good morning, procurement team.</h1></div><button className="sync" onClick={sync} disabled={loading}><RefreshCw size={17} className={loading?'spin':''}/> Sync Omni</button></header><section className="filters"><CalendarDays size={18}/><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><span>—</span><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load} className="apply">Apply filter</button><span className="currency">All values in <b>USD</b></span></section>{message&&<div className="notice">{message}</div>}<section className="stats"><div><span>Total spend</span><strong>{money(total)}</strong><small>Top 10 suppliers</small></div><div><span>Active suppliers</span><strong>{suppliers}</strong><small>In selected period</small></div><div><span>Invoices analysed</span><strong>{invoices.length}</strong><small>Converted to USD</small></div></section><section className="panel"><div className="panel-head"><div><h2>Top 10 suppliers by spend</h2><p className="muted">Transaction values converted at applicable invoice-date rates</p></div><span className="badge">{from} → {to}</span></div><div className="chart"><ResponsiveContainer width="100%" height={340}><BarChart data={ranked} layout="vertical" margin={{left:20,right:30}}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#e8edf3"/><XAxis type="number" tickFormatter={(v)=>`$${Math.round(v/1000)}k`} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="supplier" width={145} axisLine={false} tickLine={false}/><Tooltip formatter={(v:any)=>money(v)} cursor={{fill:'#f3f7f6'}}/><Bar dataKey="value" fill="#19a974" radius={[0,5,5,0]} barSize={20}/></BarChart></ResponsiveContainer></div></section></main></div> }
createRoot(document.getElementById('root')!).render(<App/>);
